apiVersion: v1
kind: Secret
metadata:
  name: learningsteps-secrets
  namespace: learningsteps
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:LearnSteps2025!@learningsteps-db.postgres.database.azure.com/learning_journal"
