apiVersion: v1
kind: Service
metadata:
  name: learningsteps-service
spec:
  type: LoadBalancer
  selector:
    app: learningsteps-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
